### ISSUE TITLE
string is not stack allocated: not supported

### ISSUE THREAD

**Issue by DavadDi** [dylandreimerink/edb#24]
```
./edb graph ./hello-debug.o hello -o aa.txt
Error: load collection: file ./hello-debug.o: section "tracepoint/syscalls/sys_enter_execve": string is not stack allocated: not supported
Usage:
  edb graph {ELF} {program name} [flags]

Flags:
  -f, --format string   The output format: dot, svg, pdf or png (default "svg")
  -h, --help            help for graph
  -o, --output string   output to given file path or - for stdout, instread of opening in browser

load collection: file ./hello-debug.o: section "tracepoint/syscalls/sys_enter_execve": string is not stack allocated: not supported
```

bpf code:
```
cat ../hello_bpf/hello.c
#include <linux/bpf.h>
#define SEC(NAME) __attribute__((section(NAME), used))

static int (*bpf_trace_printk)(const char *fmt, int fmt_size,
                               ...) = (void *)BPF_FUNC_trace_printk;

SEC("tracepoint/syscalls/sys_enter_execve")
int bpf_prog(void *ctx) {
  const char *msg = "Hello, BPF World!";
  bpf_trace_printk(msg, sizeof(msg));
  return 0;
}

char _license[] SEC("license") = "GPL";
```

Any idea? Error for bpf_trace_printk？

**Comment by dylandreimerink** [comment]
This is a limitation of eBPF / cilium/ebpf, discussed [here](https://github.com/cilium/ebpf/discussions/601).

The TLDR is that your current code will place the string in the strings section of the ELF file. For normal computer programs, the string would be placed on the heap and then a `*msg` would be set to point to this heap object. But since eBPF programs have not heap, we need to place the strings on the stack instead. Libbpf has a helper macro called [bpf_printk](https://github.com/libbpf/libbpf/blob/master/src/bpf_helpers.h#L286) which does this for you so you don't have to think about it yourself.
